### ISSUE TITLE
[feat] ui 보완

### ISSUE THREAD

**Issue by thissound22** [TEAM-ALOM/BaroMap-iOS#17]
## 👀 Issue

ui를 보완합니다.

### ✅ Todo
- [x] placeName과 사용자 입력 문자 비교하여 같은 경우 색상 강조
- [x] 중복 코드 modifier
- [x] MapSearchResultView 보완
- [x] 내 위치 버튼 커스텀
- [ ] 길찾기 버튼 기능 구현(PathListView 연결)

**Comment by thissound22** [comment]
MapSearchResultView에서의 모든 연결에 대한 구조가 필요
